services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/workspace
      - commandhistory:/commandhistory
    stdin_open: true
    tty: true

volumes:
  commandhistory:
