services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - .:/workspace
      - commandhistory:/commandhistory
    stdin_open: true
    tty: true

volumes:
  commandhistory:
